from pathlib import Path
from bs4 import BeautifulSoup
import html,json,os,re,shutil
ROOT=Path(__file__).parent; OUT=ROOT/'public'; OUT.mkdir(exist_ok=True); (OUT/'assets').mkdir(exist_ok=True)
origin='https://winchlawfirm.com'; ga=os.environ.get('GA_MEASUREMENT_ID','')
if ga and not re.fullmatch(r'G-[A-Z0-9]+',ga):raise ValueError('Invalid GA_MEASUREMENT_ID')
nav=[('Home','/'),('Landowner & Property Rights','/louisiana-landowner-bill-of-rights'),('Entergy & Utility Projects','https://entergy.winchlawfirm.com/'),('Business Legal — Handled.','https://businesslegal.winchlawfirm.com/'),('Resources','/legal-resources'),('Request a Consultation','/book-online')]
header='<a class="skip" href="#main">Skip to content</a><header><div class="bar"><a class="brand" href="/" aria-label="Winch Law Firm home"><img src="/assets/eagle.webp" width="92" height="76" alt=""><span>WINCH<small>LAW FIRM, LLC</small></span></a><button class="menu" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation">'+''.join(f'<a href="{u}">{t}</a>' for t,u in nav)+'</nav></div></header>'
footer='<footer><div class="wrap"><h2>People. Property. Justice.</h2><p>Winch Law Firm, LLC · Justin L. Winch</p><p>404 Stafford Place · New Orleans, LA 70124</p><p>General inquiries: <a href="tel:+15045001899">504-500-1899</a><br>Entergy / expropriation dedicated line: <a href="tel:+15043772620">504-377-2620</a><br><a href="mailto:justin.winch@winchlawfirm.com">justin.winch@winchlawfirm.com</a></p><p><a href="/blog">Articles</a> · <a href="/privacy">Privacy</a></p><p class="fine">General information, not legal advice. Contacting the firm does not establish an attorney-client relationship. © 2026 Winch Law Firm, LLC.</p></div></footer>'
pages=[]
def page(path,title,desc,body,noindex=False):
 url=origin+('' if path=='/' else path); analytics=''
 analytics="<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-PB4XQM3P');</script>"
 meta=f'<link rel="canonical" href="{url}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:image" content="{origin}/assets/social.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{html.escape(title)}"><meta name="twitter:description" content="{html.escape(desc)}"><meta name="twitter:image" content="{origin}/assets/social.jpg">'
 if noindex:meta+='<meta name="robots" content="noindex,follow">'
 doc=f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}">{meta}<link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script>{analytics}</head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PB4XQM3P" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>{header}<main id="main">{body}</main>{footer}</body></html>'
 dest=OUT/'index.html' if path=='/' else OUT/path.strip('/')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(doc)
 if not noindex:pages.append(path)
intro='Winch Law Firm, LLC represents landowners and businesses in matters involving pipeline servitudes, expropriation, and property rights disputes. The firm’s work focuses on ensuring that acquisition efforts proceed through lawful process, transparent valuation, and full respect for private property.'
page('/','Louisiana Landowner & Expropriation Lawyer | Winch Law Firm',intro,'<section class="hero"><div class="wrap"><p class="eyebrow">Louisiana landowners · Property rights</p><h1>Your land.<br>Your rights.<br>A clear next step.</h1><p>'+intro+'</p><div class="actions"><a class="button" href="https://entergy.winchlawfirm.com/">Received an Entergy notice?</a><a class="button secondary" href="/book-online">Request a consultation</a></div><p class="fine">Entergy and expropriation inquiries: <a href="tel:+15043772620">504-377-2620</a></p></div></section><section class="wrap"><p class="eyebrow">Find your path</p><h2>Help for the property and business questions in front of you.</h2><div class="cards"><a class="card" href="https://entergy.winchlawfirm.com/"><span>01 / LANDOWNERS</span><h3>Entergy & utility projects</h3><p>Review a notice, offer, appraisal, or proposed right-of-way.</p></a><a class="card" href="https://entergybabelwebre.winchlawfirm.com/"><span>02 / PROJECT INFORMATION</span><h3>Babel–Webre transmission line</h3><p>Information for property owners affected by the proposed project.</p></a><a class="card" href="https://businesslegal.winchlawfirm.com/"><span>03 / BUSINESS</span><h3>Business Legal — Handled.</h3><p>Visit the firm’s dedicated business legal website.</p></a></div></section><section class="wrap band"><h2>Understand the documents before your next decision.</h2><p>Start with the firm’s published landowner resources and practical review guides.</p><a href="/legal-resources">Explore landowner resources →</a></section>')
def clean_blocks(container):
 result=[]
 for x in container.find_all(['h2','h3','p','ul','ol','figure']):
  if any(a.name in ['ul','ol','figure'] for a in x.parents if a!=container):continue
  if not x.get_text(strip=True).replace('\u200b','') and x.name!='figure':continue
  y=BeautifulSoup(str(x),'html.parser')
  for el in y.find_all(True):
   el.attrs={k:v for k,v in el.attrs.items() if k in ['href','src','alt']}
   if el.name=='a' and el.get('href','').startswith(origin):el['href']=el['href'][len(origin):] or '/book-online'
  result.append(str(y))
 return ''.join(result)
s=BeautifulSoup((ROOT/'migration/louisiana-landowner-bill-of-rights.html').read_text(),'html.parser')
page('/louisiana-landowner-bill-of-rights','Louisiana Landowner Bill of Rights | Winch Law Firm','The firm’s published guide to Louisiana pipeline servitudes, property rights, and expropriation.','<article class="wrap prose"><p class="eyebrow">Landowner resource</p><h1>Louisiana Landowners’ Bill of Rights</h1>'+clean_blocks(s.find('main'))+'<p><a class="button" href="https://entergy.winchlawfirm.com/">Review an Entergy notice or offer</a></p></article>')
posts=[('received-utility-right-of-way-offer-letter-louisiana','Received a Utility Right-of-Way Offer Letter? Your Next Steps'),('should-i-sign-utility-servitude-agreement-louisiana','Should I Sign a Utility Servitude Agreement in Louisiana?')]
for slug,title in posts:
 s=BeautifulSoup((ROOT/'migration'/f'{slug}.html').read_text(),'html.parser');a=s.find('article');content=a.find(attrs={'data-hook':'post-content'}) or a
 page('/post/'+slug,title+' | Winch Law Firm','Practical document-review information for Louisiana landowners facing utility acquisitions.','<article class="wrap prose"><p class="eyebrow">By Justin L. Winch · Winch Law Firm, LLC</p><h1>'+title+'</h1>'+clean_blocks(content)+'</article>')
postlinks=''.join(f'<a class="card" href="/post/{slug}"><h3>{title}</h3><p>Read the guide →</p></a>' for slug,title in posts)
page('/blog','Landowner Articles | Winch Law Firm','Published articles about Louisiana utility offers and servitude agreements.','<section class="wrap"><h1>Landowner articles</h1><div class="cards">'+postlinks+'</div></section>')
page('/legal-resources','Louisiana Property Rights Resources | Winch Law Firm','Landowner rights, utility offer review, and servitude agreement resources.','<section class="wrap"><p class="eyebrow">Resources</p><h1>Make sense of the next step.</h1><div class="cards"><a class="card" href="/louisiana-landowner-bill-of-rights"><h3>Louisiana Landowner Bill of Rights</h3><p>Read the firm’s published resource.</p></a>'+postlinks+'</div></section>')
omega_sources='''<div class="source-list"><a class="card" href="https://lpscpubvalence.lpsc.louisiana.gov/portal/PSC/DocketDetails?docketId=32146" target="_blank" rel="noopener"><span>LOUISIANA PUBLIC SERVICE COMMISSION</span><h3>Docket U-37882</h3><p>Entergy Louisiana’s application for generation and transmission resources connected to the North Louisiana data-center project.</p></a><a class="card" href="https://lpscpubvalence.lpsc.louisiana.gov/portal/PSC/DocumentDetails?documentId=180141" target="_blank" rel="noopener"><span>LPSC ORDER</span><h3>Order No. U-37882</h3><p>Procedural order establishing the evidentiary record and schedule for Commission consideration.</p></a><a class="card" href="https://lpscpubvalence.lpsc.louisiana.gov/portal/PSC/ViewFile?fileId=kt5JixLAYFY%3D" target="_blank" rel="noopener"><span>PUBLIC FILING</span><h3>Transmission project testimony</h3><p>Public testimony describing the West Fork Creek–St. Landry 500-kV line and related facilities.</p></a><a class="card" href="https://www.entergy.com/news/entergy-louisiana-announces-a-new-agreement-with-meta-that-will-deliver-an-additional-2b-in-customer-savings" target="_blank" rel="noopener"><span>ENTERGY</span><h3>Project announcement</h3><p>Entergy’s announcement of the broader infrastructure buildout supporting Meta’s North Louisiana data center.</p></a><a class="card" href="https://power-viz.com/babel-webre/index.php" target="_blank" rel="noopener"><span>ROUTE MAP RESOURCE</span><h3>Interactive transmission map</h3><p>Use the interactive map as a visual reference, then confirm the current route against filed materials.</p></a></div>'''
page('/west-fork-creek','West Fork Creek–Boeuf 500-kV Transmission Project | Project Omega','Information for Louisiana landowners about the proposed West Fork Creek transmission corridor through LaSalle and neighboring parishes.','''<section class="hero"><div class="wrap"><p class="eyebrow">LaSalle · Rapides · Avoyelles · Caldwell · Richland</p><h1>West Fork Creek–Boeuf<br>500-kV Transmission Project</h1><p class="lede">Project Omega is the public name being used for the proposed high-voltage transmission corridor connecting the West Fork Creek area toward the North Louisiana data-center development.</p><div class="actions"><a class="button" href="/book-online">Request a property-rights review</a><a class="button secondary" href="#records">View the public record</a></div><p class="fine">Entergy / expropriation inquiries: <a href="tel:+15043772620">504-377-2620</a></p></div></section><section class="wrap prose"><p class="eyebrow">What the records show</p><h2>One project, several names.</h2><p>Public reporting and landowner route materials refer to the corridor as the <strong>West Fork Creek–Boeuf 500-kV Transmission Project</strong> or <strong>Project Omega</strong>. The Louisiana Public Service Commission filings use the related description <strong>West Fork Creek–St. Landry 500 kV</strong> within the broader Evest/Meta infrastructure case, LPSC Docket U-37882.</p><p>Because route descriptions and engineering plans can change, a parcel should be evaluated against the current route materials—not against a general project summary or a verbal description alone.</p><div class="callout"><strong>If surveyors, acquisition agents, or Entergy representatives have contacted you, preserve every letter, map, survey notice, offer, appraisal, and right-of-way document.</strong><br><a href="/book-online">Ask the firm to review the materials.</a></div></section><section class="wrap"><p class="eyebrow">Public documents & links</p><h2 id="records">Start with the record.</h2><p class="muted">These links open the public sources currently identified for the project. LPSC filings may include public redactions and separate exhibits.</p>'''+omega_sources+'''</section><section class="wrap band"><h2>Is your property near the proposed corridor?</h2><p>The existence of a proposed route does not answer what rights may be acquired, what interests may be affected, or what compensation may be owed. Those questions turn on the documents and the property.</p><a class="button" href="/book-online">Request a consultation</a></section>''')
form='''<form name="consultation" method="POST" action="/thank-you" data-netlify="true" netlify-honeypot="website" enctype="multipart/form-data"><input type="hidden" name="form-name" value="consultation"><p hidden><label>Leave this blank<input name="website"></label></p><label>Your name<input name="name" autocomplete="name" required maxlength="150"></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Phone<input name="phone" type="tel" autocomplete="tel"></label><label>What would you like to discuss?<select name="topic" required><option value="">Select a topic</option><option>Entergy / expropriation</option><option>Landowner / property damage</option><option>Business legal</option><option>Other</option></select></label><label>Brief description<textarea name="message" rows="5" maxlength="4000" required></textarea></label><label>Notice or appraisal (optional; PDF or image, up to 4 MB)<input name="document" type="file" accept=".pdf,.png,.jpg,.jpeg"></label><p class="fine">Please omit Social Security numbers, financial account details, and other unnecessary sensitive information. Do not rely on this form for a court deadline. A consultation request is not an appointment or an agreement to represent you.</p><label class="consent"><input type="checkbox" name="acknowledgment" required>I understand this is a request for contact and have read the <a href="/privacy">privacy information</a>.</label><p id="form-status" role="status" aria-live="polite"></p><button class="button" type="submit">Send consultation request</button></form>'''
page('/book-online','Request a Consultation | Winch Law Firm','Contact Winch Law Firm about a Louisiana property, expropriation, or business matter.','<section class="wrap prose"><p class="eyebrow">Contact the firm</p><h1>Request a consultation.</h1><p>For Entergy or expropriation matters, the dedicated line is <a href="tel:+15043772620">504-377-2620</a>. General inquiries: <a href="tel:+15045001899">504-500-1899</a>.</p>'+form+'</section>')
page('/privacy','Website Privacy Information | Winch Law Firm','Information about consultation requests and website analytics.','<article class="wrap prose"><h1>Website privacy information</h1><p>This website offers a contact form for requesting a response from Winch Law Firm. Information you submit is processed through the website hosting provider, Netlify, and made available to the firm for responding to your request. An uploaded document is included with the submission.</p><p>Submit only information needed for an initial inquiry. Contact the firm before transmitting sensitive records that require a different delivery method. Submission does not establish an attorney-client relationship.</p><p>When configured, Google Analytics records website activity to help evaluate how visitors find and use the site. Names, email addresses, messages, and document contents are not included in the analytics events implemented on this site.</p><p>Questions: <a href="mailto:justin.winch@winchlawfirm.com">justin.winch@winchlawfirm.com</a>.</p></article>')
page('/thank-you','Request Received | Winch Law Firm','Consultation request confirmation.','<section class="wrap prose"><h1>Your request was submitted.</h1><p>This does not confirm an appointment or representation. If a deadline is approaching, call the firm rather than waiting for a response.</p><a href="/">Return home</a></section>',True)
page('/404','Page Not Found | Winch Law Firm','Find the firm’s property rights resources and contact information.','<section class="wrap prose"><h1>Let’s find the right page.</h1><p>This address does not match a page on this website.</p><a class="button" href="/legal-resources">Browse resources</a> <a href="/book-online">Contact the firm</a></section>',True)
shutil.copyfile(OUT/'404/index.html',OUT/'404.html')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+origin+'/sitemap.xml\n')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+origin+('' if p=='/' else p)+'</loc></url>' for p in pages)+'</urlset>')
subdomain_urls=['https://entergy.winchlawfirm.com/','https://entergybabelwebre.winchlawfirm.com/','https://businesslegal.winchlawfirm.com/']
(OUT/'subdomains-sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in subdomain_urls)+'</urlset>')
(OUT/'_redirects').write_text('/entergy-property-rights-review https://entergy.winchlawfirm.com/ 301\n/entergy-rights-review https://entergy.winchlawfirm.com/ 301\n/notifications /book-online 301\n/profile/justin-winch62979/profile / 301\n/privacy.html /privacy 301\n/thank-you.html /thank-you 301\n')
for src,dest in [('WLF_Eagle_Web_Transparent.webp','eagle.webp'),('WLF_Eagle_Social_Hunter_Green_1200x630.jpg','social.jpg')]:
 source=ROOT/'brand'/src
 if source.exists():shutil.copyfile(source,OUT/'assets'/dest)
shutil.copytree(ROOT/'src-assets',OUT/'assets',dirs_exist_ok=True)
print(f'Built {len(pages)} indexed pages; analytics '+('configured' if ga else 'NOT CONFIGURED — live verification required'))
